description: Default Linux machine executor for Dagger workflows

parameters:
  tag:
    type: string
    default: "current"
    description: "The tag for the Ubuntu machine image"
  resource_class:
    type: string
    default: "medium"
    description: "The resource class for the executor (e.g., small, medium, large, xlarge)"
  docker_layer_caching:
    type: boolean
    default: false
    description: "Enable Docker Layer Caching to speed up Docker builds"

machine:
  image: ubuntu-2404:<< parameters.tag >>
  docker_layer_caching: << parameters.docker_layer_caching >>

resource_class: << parameters.resource_class >>
